### ISSUE TITLE
Byte Order Mark at the Beginning of Controller.py

### ISSUE THREAD

**Issue by vdaneshmand** [ipop-project/controllers#62]
There is a BOM character at the beginning of Controller.py in the controller package, probably written by Visual Studio. It's just visible in Hex editors and doesn't have a negative effect on the file as long as we run the script using Python. But if someone tries to execute the file directly, as I usually do, that causes an error which may be too confusing. There may be similar situations in other files, as well. I think we should remove it to prevent this type of problems.

**Comment by kcratie** [comment]
Fixed b7fa49a
