### ISSUE TITLE
Sample Config Files Not Updated

### ISSUE THREAD

**Issue by vdaneshmand** [ipop-project/controllers#64]
I think we should update the sample config files based on the latest default settings:

> "num_successors": 8,
> "num_chords": 8,
> "num_on_demand": 20,
> "num_inbound": 40,
> "ttl_on_demand": 6000,

controllers/controller/modules/sample-gvpn-config.json
controllers/controller/modules/sample-svpn-config.json

**Comment by kcratie** [comment]
Appropriate values discussed by @vdaneshmand, @renatof, @ssabogal
